# Generated by Django 5.2.8 on 2025-11-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contactinfo_feedback_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
