# Generated by Django 5.2.8 on 2025-12-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
